#!/usr/bin/env python3
"""Scrape every tradeable (buyable) item's id and English name into a C++ header.

Pipeline
--------
1. Ask the official GW2 API for every item id that has trading-post price data
   (``commerce/prices`` returns the full list of tradeable ids).
2. Resolve the English name of each id in batches via ``items?lang=en&ids=``.
3. Write the ``id -> name`` pairs to ``src/ItemNames.h``.

Run this on a network that can reach ``api.guildwars2.com`` (a corporate proxy
may block it).

Examples
--------
    py scripts/scrape_tradeable_items.py
    py scripts/scrape_tradeable_items.py --insecure   # skip TLS verification
"""

from __future__ import annotations

import argparse
from pathlib import Path
import time

import requests

GW2_API = "https://api.guildwars2.com/v2"
BATCH_SIZE = 200

USER_AGENT = "GW2TP-item-scraper/1.0 (https://github.com/franneck94/Gw2TP)"


def make_session(insecure: bool) -> requests.Session:
    session = requests.Session()
    session.headers.update({"User-Agent": USER_AGENT})
    if insecure:
        session.verify = False
        requests.packages.urllib3.disable_warnings()  # type: ignore[attr-defined]
    return session


def get_json(session: requests.Session, url: str, params: dict):
    for attempt in range(4):
        try:
            response = session.get(url, params=params, timeout=30)
            response.raise_for_status()
            return response.json()
        except requests.RequestException:
            if attempt == 3:
                raise
            time.sleep(1.5 * (attempt + 1))
    return []


def fetch_tradeable_ids(session: requests.Session) -> list[int]:
    print("API: listing tradeable item ids (commerce/prices)")
    ids = get_json(session, f"{GW2_API}/commerce/prices", {})
    ids = [int(item_id) for item_id in ids]
    print(f"API: {len(ids)} tradeable ids")
    return ids


def fetch_names(session: requests.Session, ids: list[int]) -> dict[int, str]:
    names: dict[int, str] = {}
    for start in range(0, len(ids), BATCH_SIZE):
        chunk = ids[start : start + BATCH_SIZE]
        payload = get_json(
            session,
            f"{GW2_API}/items",
            {"lang": "en", "ids": ",".join(str(item_id) for item_id in chunk)},
        )
        if not isinstance(payload, list):
            continue
        for item in payload:
            item_id = item.get("id")
            name = item.get("name", "")
            if item_id is not None and name:
                names[int(item_id)] = name
        print(f"API: resolved {len(names)}/{len(ids)} names", end="\r")
    print()
    return names


def write_header(output: Path, names: dict[int, str]) -> None:
    def escape(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"')

    lines = [
        "// Auto-generated by scripts/scrape_tradeable_items.py — do not edit by hand.",
        f"// Tradeable items: {len(names)}",
        "",
        "#pragma once",
        "",
        "#include <map>",
        "#include <string>",
        "",
        "namespace ItemNames",
        "{",
        "    inline const std::map<int, std::string> NAMES = {",
    ]
    for item_id in sorted(names):
        lines.append(f'        {{{item_id}, "{escape(names[item_id])}"}},')
    lines.append("    };")
    lines += ["}", ""]
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output} ({len(names)} items)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Disable TLS certificate verification (corporate proxies).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "src" / "ItemNames.h",
        help="Header file to write.",
    )
    args = parser.parse_args()

    session = make_session(args.insecure)

    ids = fetch_tradeable_ids(session)
    names = fetch_names(session, ids)
    write_header(args.output, names)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
